from __future__ import annotations

TEXT = {
    "zh": {
        "browse":"浏览…","folder":"选择文件夹","save":"选择保存文件","image":"选择图片","image_filter":"图片 (*.jpg *.jpeg *.png *.bmp *.tif *.tiff *.webp);;所有文件 (*)","image_filter_short":"图片 (*.jpg *.jpeg *.png *.bmp *.tif *.tiff *.webp)",
        "preview":"在图片上拖动选择范围","preview_help":"左键拖动选择；滚轮或 +/- 缩放。已有有效数值时自动框出对应范围。","fit":"适应窗口","range":"当前范围：x={x}, y={y}, 宽={w}, 高={h}","whole":"当前范围：整张图片","preview_fail":"无法打开预览",
        "x":"x","y":"y","w":"宽","h":"高","pick":"在图片上选择…","match_group":"匹配范围与精度","template":"sample 有效范围：","template_hint":"宽/高为 0：使用整张 sample","search_mask":"被遍历图片遮蔽范围：","search_note":"每边遮蔽比例；16.67% = 搜索中央约 2/3 × 2/3","choose_target":"选择一张有代表性的被遍历图片","search_help":"拖框后按四边距离平均值换算为每边遮蔽百分比。","edge":"sample 边缘屏蔽：","similarity":"最低相似度：",
        "paths":"文件位置","sample":"sample 图片：","input":"遍历文件夹（含子文件夹）：","output":"裁切图片保存文件夹：","output_group":"输出设置","quality":"JPEG 保存质量：","name_note":"命名：1/100s + abc.jpg → 1_100_abc.jpg；无 EXIF 时使用 unknown_。",
        "start":"开始处理","cancel":"取消","debug":"Debug 模式","debug_tip":"保存压缩后的二值化、遮蔽范围、裁切框和识别点参考图","threads":"并行线程：","threads_tip":"大图内存占用高，默认 2 线程。","wait_cancel":"正在等待当前并行任务处理完毕后取消…",
        "missing":"信息不完整","select_missing":"请选择：{items}","finished":"处理结束：成功 {ok}，未达阈值 {skip}，失败 {fail}。","done":"处理完成","done_body":"共 {total} 张\n成功：{ok}\n未达阈值：{skip}\n失败：{fail}\n\n保存位置：{path}{debug}","debug_line":"\nDebug：{path}","failed_title":"处理未完成","cancelled":"处理已取消。已经保存的文件不会被删除。",
        "center_group":"从图片中心裁切","fixed":"固定像素","ratio":"原图比例","ratio_label":"宽、高均取原图的：","ratio_ph":"例如 1/3、1/4 或 0.5","center_note":"裁切区域始终居中；文件名使用“快门速度_原文件名”。",
        "crop_preview":"裁切预览…","choose_crop_preview":"选择一张遍历图片进行裁切预览","crop_preview_title":"中心裁切预览","crop_preview_help":"亮区是最终保留的中心裁切范围，暗区会被裁掉。滚轮或 +/- 可缩放查看。","crop_preview_info":"原图：{iw} × {ih} px；保留范围：x={x}, y={y}, 宽={w}, 高={h}",
        "csv":"CSV 保存位置：","csv_filter":"CSV 文件 (*.csv)","coord_note":"CSV 三列：文件名、x坐标、y坐标。坐标是 sample 中心点在被遍历图片中的像素位置；未匹配图片坐标为空。",
        "resize_group":"图片压缩设置","resize_ratio":"缩放比例：","resize_ratio_note":"默认 0.25，即宽和高均缩小到原来的 25%。","resize_source_note":"按照来源 Tool 7，只递归处理 .jpg 文件。","resize_output_note":"输出到每张原图所在目录下的 resize_images 文件夹；文件名和扩展名保持不变。","resize_ratio_positive":"缩放比例必须大于 0。","resize_write_failed":"无法保存压缩图片：{path}","resize_done":"完成：{name}","resize_output_multiple":"各原图目录下的 resize_images 文件夹（遍历根目录：{root}）",
        "tab1":"① 相似区域裁切","tab2":"② 中心裁切","tab3":"③ 坐标导出","tab4":"④ 图片压缩","status":"支持 JPG / PNG / BMP / TIFF / WebP；递归遍历子文件夹。","language":"界面语言：","running":"仍在处理","running_msg":"任务仍在运行。请先取消并等待当前图片处理结束，再关闭程序。",
        "range_out":"指定范围不在图片内","folder_missing":"图片文件夹不存在：{path}","read_fail":"无法读取图片：{path}","encode_fail":"无法编码输出图片：{path}","template_small":"屏蔽边缘后模板过小，请减小屏蔽比例或扩大模板范围","search_small":"搜索范围小于有效模板范围","edge_crop":"匹配位置靠近边缘，无法裁出完整 sample 范围","ratio_format":"比例请输入 1/3、1/4 或 0.5","ratio_range":"裁切比例必须大于 0 且不超过 1","fixed_positive":"固定像素模式下，宽度和高度必须大于 0","fixed_large":"指定裁切像素大于原图","skip":"跳过（相似度 {score:.3f}）：{name}","ok_score":"完成（相似度 {score:.3f}）：{name}","ok":"完成：{name}","fail":"失败：{name} — {error}","record":"已记录（相似度 {score:.3f}）：{name}","below":"未达阈值（{score:.3f}）：{name}","csv_header":("文件名","x坐标","y坐标"),
    },
    "ja": {
        "browse":"参照…","folder":"フォルダーを選択","save":"保存先を選択","image":"画像を選択","image_filter":"画像 (*.jpg *.jpeg *.png *.bmp *.tif *.tiff *.webp);;すべてのファイル (*)","image_filter_short":"画像 (*.jpg *.jpeg *.png *.bmp *.tif *.tiff *.webp)",
        "preview":"画像上でドラッグして範囲を選択","preview_help":"左ボタンでドラッグして選択。ホイールまたは +/- で拡大・縮小します。有効な既存値は自動表示します。","fit":"ウィンドウに合わせる","range":"現在の範囲：x={x}, y={y}, 幅={w}, 高さ={h}","whole":"現在の範囲：画像全体","preview_fail":"プレビューを開けません",
        "x":"x","y":"y","w":"幅","h":"高さ","pick":"画像上で選択…","match_group":"一致範囲と精度","template":"sample 有効範囲：","template_hint":"幅/高さが 0：sample 全体を使用","search_mask":"対象画像の除外範囲：","search_note":"各辺の除外率。16.67% = 中央のおよそ 2/3 × 2/3 を検索","choose_target":"代表的な対象画像を1枚選択","search_help":"ドラッグ範囲から四辺までの距離平均を各辺の除外率へ換算します。","edge":"sample 周辺除外：","similarity":"最低類似度：",
        "paths":"ファイル位置","sample":"sample 画像：","input":"対象フォルダー（サブフォルダー含む）：","output":"切り抜き画像の保存先：","output_group":"出力設定","quality":"JPEG 保存品質：","name_note":"命名：1/100s + abc.jpg → 1_100_abc.jpg。EXIF がない場合は unknown_。",
        "start":"処理開始","cancel":"キャンセル","debug":"Debug モード","debug_tip":"二値化、除外範囲、切り抜き枠、検出点の圧縮参考画像を保存します","threads":"並列スレッド：","threads_tip":"高解像度画像はメモリを多く使用します。既定値は 2。","wait_cancel":"実行中の並列処理が終了してからキャンセルします…",
        "missing":"入力情報が不足しています","select_missing":"選択してください：{items}","finished":"処理完了：成功 {ok}、しきい値未満 {skip}、失敗 {fail}。","done":"処理完了","done_body":"合計 {total} 枚\n成功：{ok}\nしきい値未満：{skip}\n失敗：{fail}\n\n保存先：{path}{debug}","debug_line":"\nDebug：{path}","failed_title":"処理が完了していません","cancelled":"処理をキャンセルしました。保存済みファイルは削除されません。",
        "center_group":"画像中心から切り抜き","fixed":"固定ピクセル","ratio":"元画像比率","ratio_label":"幅・高さを元画像の比率で指定：","ratio_ph":"例：1/3、1/4、0.5","center_note":"切り抜き範囲は常に中央です。ファイル名は「シャッター速度_元ファイル名」です。",
        "crop_preview":"切り抜きプレビュー…","choose_crop_preview":"切り抜きプレビュー用の対象画像を1枚選択","crop_preview_title":"中央切り抜きプレビュー","crop_preview_help":"明るい部分が最終的に残る中央切り抜き範囲で、暗い部分は切り落とされます。ホイールまたは +/- で拡大・縮小できます。","crop_preview_info":"元画像：{iw} × {ih} px；残す範囲：x={x}, y={y}, 幅={w}, 高さ={h}",
        "csv":"CSV 保存先：","csv_filter":"CSV ファイル (*.csv)","coord_note":"CSV は「ファイル名、x座標、y座標」の3列。座標は対象画像内の sample 中心位置で、不一致画像は空欄です。",
        "resize_group":"画像圧縮設定","resize_ratio":"リサイズ比率：","resize_ratio_note":"既定値は 0.25。幅と高さを元画像の 25% に縮小します。","resize_source_note":"元の Tool 7 と同様に、.jpg ファイルのみをサブフォルダーまで再帰処理します。","resize_output_note":"各元画像と同じ階層に resize_images フォルダーを作成し、ファイル名と拡張子は変更しません。","resize_ratio_positive":"リサイズ比率は 0 より大きくしてください。","resize_write_failed":"圧縮画像を保存できません：{path}","resize_done":"完了：{name}","resize_output_multiple":"各元画像フォルダー内の resize_images（対象ルート：{root}）",
        "tab1":"① 類似領域切り抜き","tab2":"② 中央切り抜き","tab3":"③ 座標出力","tab4":"④ 画像圧縮","status":"JPG / PNG / BMP / TIFF / WebP 対応。サブフォルダーまで再帰処理します。","language":"表示言語：","running":"処理中です","running_msg":"処理が実行中です。先にキャンセルし、現在の画像処理終了後に閉じてください。",
        "range_out":"指定範囲が画像内にありません","folder_missing":"画像フォルダーが存在しません：{path}","read_fail":"画像を読み込めません：{path}","encode_fail":"出力画像をエンコードできません：{path}","template_small":"周辺除外後のテンプレートが小さすぎます。除外率を下げるか有効範囲を広げてください","search_small":"検索範囲が有効テンプレートより小さいです","edge_crop":"一致位置が画像端に近いため sample 全体を切り出せません","ratio_format":"比率は 1/3、1/4、0.5 のように入力してください","ratio_range":"切り抜き比率は 0 より大きく 1 以下にしてください","fixed_positive":"固定ピクセルモードでは幅と高さを 0 より大きくしてください","fixed_large":"指定した切り抜きサイズが元画像より大きいです","skip":"スキップ（類似度 {score:.3f}）：{name}","ok_score":"完了（類似度 {score:.3f}）：{name}","ok":"完了：{name}","fail":"失敗：{name} — {error}","record":"記録済み（類似度 {score:.3f}）：{name}","below":"しきい値未満（{score:.3f}）：{name}","csv_header":("ファイル名","x座標","y座標"),
    },
    "en": {
        "browse":"Browse…","folder":"Select folder","save":"Select save file","image":"Select image","image_filter":"Images (*.jpg *.jpeg *.png *.bmp *.tif *.tiff *.webp);;All files (*)","image_filter_short":"Images (*.jpg *.jpeg *.png *.bmp *.tif *.tiff *.webp)",
        "preview":"Drag on the image to select a region","preview_help":"Drag with the left mouse button to select; use the wheel or +/- to zoom. Existing valid values are shown automatically.","fit":"Fit to window","range":"Current region: x={x}, y={y}, width={w}, height={h}","whole":"Current region: whole image","preview_fail":"Unable to open preview",
        "x":"x","y":"y","w":"Width","h":"Height","pick":"Select on image…","match_group":"Matching region and accuracy","template":"Valid sample region:","template_hint":"Width/height 0: use the entire sample","search_mask":"Target image edge mask:","search_note":"Mask percentage on each side; 16.67% searches roughly the center 2/3 × 2/3","choose_target":"Select a representative target image","search_help":"The selected rectangle is converted to an average edge-mask percentage from the four sides.","edge":"Sample edge mask:","similarity":"Minimum similarity:",
        "paths":"File locations","sample":"Sample image:","input":"Input folder (including subfolders):","output":"Crop output folder:","output_group":"Output settings","quality":"JPEG save quality:","name_note":"Naming: 1/100s + abc.jpg → 1_100_abc.jpg; unknown_ is used when EXIF is unavailable.",
        "start":"Start","cancel":"Cancel","debug":"Debug mode","debug_tip":"Save downscaled reference images for binarization, masks, crop rectangles and detected points","threads":"Parallel threads:","threads_tip":"Large images use substantial memory; default is 2 threads.","wait_cancel":"Waiting for current parallel work to finish before cancelling…",
        "missing":"Missing information","select_missing":"Please select: {items}","finished":"Finished: success {ok}, below threshold {skip}, failed {fail}.","done":"Completed","done_body":"Total: {total}\nSuccess: {ok}\nBelow threshold: {skip}\nFailed: {fail}\n\nSaved to: {path}{debug}","debug_line":"\nDebug: {path}","failed_title":"Processing not completed","cancelled":"Processing was cancelled. Files already saved are not deleted.",
        "center_group":"Crop from image center","fixed":"Fixed pixels","ratio":"Original-image ratio","ratio_label":"Use this ratio for both width and height:","ratio_ph":"For example 1/3, 1/4 or 0.5","center_note":"The crop is always centered; filenames use shutter-speed_original-name.",
        "crop_preview":"Crop preview…","choose_crop_preview":"Select an input image for crop preview","crop_preview_title":"Center crop preview","crop_preview_help":"The bright area is retained and the dark area is cropped away. Use the wheel or +/- to zoom.","crop_preview_info":"Original: {iw} × {ih} px; retained region: x={x}, y={y}, width={w}, height={h}",
        "csv":"CSV save location:","csv_filter":"CSV files (*.csv)","coord_note":"CSV columns: filename, x coordinate, y coordinate. Coordinates are the sample center in each target image; unmatched coordinates are blank.",
        "resize_group":"Image compression settings","resize_ratio":"Resize ratio:","resize_ratio_note":"Default is 0.25, reducing both width and height to 25% of the original.","resize_source_note":"As in the source Tool 7, only .jpg files are processed recursively.","resize_output_note":"A resize_images folder is created beside each source image; filename and extension are preserved.","resize_ratio_positive":"Resize ratio must be greater than 0.","resize_write_failed":"Unable to save resized image: {path}","resize_done":"Completed: {name}","resize_output_multiple":"resize_images folders beside each source image (input root: {root})",
        "tab1":"① Similar-region crop","tab2":"② Center crop","tab3":"③ Coordinate export","tab4":"④ Image compression","status":"Supports JPG / PNG / BMP / TIFF / WebP; recursively scans subfolders.","language":"Interface language:","running":"Processing is still running","running_msg":"A task is still running. Cancel it and wait for the current image to finish before closing the application.",
        "range_out":"The specified region is outside the image","folder_missing":"Image folder does not exist: {path}","read_fail":"Unable to read image: {path}","encode_fail":"Unable to encode output image: {path}","template_small":"The template is too small after edge masking; reduce the mask or enlarge the template region","search_small":"The search region is smaller than the effective template","edge_crop":"The match is too close to the edge to crop the full sample region","ratio_format":"Enter a ratio such as 1/3, 1/4 or 0.5","ratio_range":"Crop ratio must be greater than 0 and no more than 1","fixed_positive":"In fixed-pixel mode, width and height must be greater than 0","fixed_large":"The requested crop size is larger than the source image","skip":"Skipped (similarity {score:.3f}): {name}","ok_score":"Completed (similarity {score:.3f}): {name}","ok":"Completed: {name}","fail":"Failed: {name} — {error}","record":"Recorded (similarity {score:.3f}): {name}","below":"Below threshold ({score:.3f}): {name}","csv_header":("Filename","X coordinate","Y coordinate"),
    },
}


def tr(lang: str, key: str, **kwargs):
    language = lang if lang in TEXT else "zh"
    value = TEXT[language][key]
    return value.format(**kwargs) if isinstance(value, str) else value
